apiVersion: v1
kind: Namespace
metadata:
  name: go-eight-ball
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: go-eight-ball
  name: go-eight-ball-deployment
  labels:
    app: go-eight-ball
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: go-eight-ball
  template:
    metadata:
      labels:
        app: go-eight-ball
    spec:
      containers:
      - image: smdeeg/go-eight-ball:go-buildpack
        name: go-eight-ball
---
apiVersion: v1
kind: Service
metadata:
  namespace: go-eight-ball
  name: go-eight-ball-lb
spec:
  ports:
    - name: go-eight-ball-svc-ports
      port: 80
      targetPort: 8090
      protocol: TCP
  selector:
    app: go-eight-ball
  type: LoadBalancer
status:
  loadBalancer: {}
