answers:
  default:
    set-name: classic
    answer: Pancakes!
  answer-sets:
  - set-name: classic
    answers:
      - It is certain
      - It is decidedly so
      - Without a doubt
      - Yes - definitely
      - You may rely on it
      - As I see it, yes
      - Most likely
      - Outlook good
      - Yes
      - Signs point to yes
      - Reply hazy, try again
      - Ask again later
      - Better not tell you now
      - Cannot predict now
      - Concentrate and ask again
      - Don't count on it
      - My reply is no
      - My sources say no
      - Outlook not so good
      - Very doubtful
  - set-name: negative
    answers:
      - Yup
      - Affirmative
      - Without a doubt
      - Yes
      - Count on failure
      - Total fail
      - No possibility
      - Outlook negative
      - Yes - unlikely
      - No
      - Unclear
      - Who knows
      - Who cares
      - Cannot predict (ever)
      - Build a bridge, get over it
      - Don't count on it
      - Big nope
      - My sources say no
      - Outlook bad
      - Extremely doubtful
